name: Release publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn build
          yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Extract PACKAGE_VERSION
        run: echo ::set-env name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")
      - name: Publish
        if: contains(env.PACKAGE_VERSION, 'dev') != true
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
      - name: Extract PACKAGE_VERSION
        run: echo ::set-env name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")
      - name: Publish
        if: contains(env.PACKAGE_VERSION, 'dev') != true
        run: |
          yarn install --frozen-lockfile
          yarn build
          npm init --scope=nrchkb -y
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHUB_TKN}}
